<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\plugin\BTCPayServer.Plugins.BareBitcoin.csproj">
            <Private>true</Private>
            <ExcludeAssets>none</ExcludeAssets>
        </ProjectReference>
        <ProjectReference Include="..\..\btcpayserver\BTCPayServer\BTCPayServer.csproj"
                          Condition="Exists('..\..\btcpayserver\BTCPayServer\BTCPayServer.csproj')">
            <Properties>StaticWebAssetsEnabled=false</Properties>
            <Private>false</Private>
        </ProjectReference>
        <ProjectReference Include="..\submodules\btcpayserver\BTCPayServer\BTCPayServer.csproj"
                          Condition="!Exists('..\..\btcpayserver\BTCPayServer\BTCPayServer.csproj') and Exists('..\submodules\btcpayserver\BTCPayServer\BTCPayServer.csproj')">
            <Properties>StaticWebAssetsEnabled=false</Properties>
            <Private>false</Private>
        </ProjectReference>
    </ItemGroup>


</Project>
